module.exports = {
  "TWILIO_ACCOUNT_SID": "YOUR_TWILIO_ACCOUNT_SID",
  "TWILIO_AUTH_TOKEN": "YOUR_TWILIO_AUTH_TOKEN",
  "TWILIO_NOTIFY_SERVICE_SID": "YOUR_NOTIFY_SERVICE_SID",
  "MARKETING_PHONE_NUMBER": "INSERT_A_TWILIO_NUMBER_FROM_YOUR_ACCOUNT",
  "SECRET": "INSERT_YOUR_PASSPORT_JS_SECRET",
  "CLIENT_ID": "INSERT_YOUR_GOOGLE_CLIENT_ID",
  "CLIENT_SECRET": "INSERT_YOUR_GOOGLE_CLIENT_SECRET",
  "CALLBACK_URL": "http://localhost:3000/auth/google/callback/",
  "FB_ACCESS_TOKEN": "INSERT_YOUR_FB_ACCESS_TOKEN",
}
